In [1]:
import os
import numpy as np
import pandas as pd

import sklearn
from sklearn.model_selection import train_test_split
from sklearn import linear_model
from sklearn.utils import shuffle
from sklearn import preprocessing

In [2]:
# Reading Data frame
df = pd.read_csv('Placement.csv')
df = df.iloc[:, 1:14]


In [3]:
le = preprocessing.LabelEncoder()
for column in range(len(df.columns)):
    df.iloc[:, column] = le.fit_transform(list(df.iloc[:, column]))


In [4]:
predict = df['status']
print(df.head(5))
x = np.array(df.iloc[:,1:13])
y = np.array(predict)
print(x)
print(y)

   gender  ssc_p  ssc_b  hsc_p  hsc_b  hsc_s  degree_p  degree_t  workex  \
0       1     46      1     93      1      1        14         2       0   
1       1     82      0     79      1      2        74         2       1   
2       1     42      0     51      0      0        27         0       0   
3       1     22      0     14      0      2         3         2       0   
4       1     98      0     70      0      1        65         0       0   

   etest_p  specialisation  mba_p  status  
0        9               1     64       1  
1       74               0    153       1  
2       55               0     50       1  
3       37               1     72       0  
4       96               0     28       1  
[[ 46   1  93 ...   1  64   1]
 [ 82   0  79 ...   0 153   1]
 [ 42   0  51 ...   0  50   1]
 ...
 [ 46   1  49 ...   0 179   1]
 [ 64   1  45 ...   1  81   1]
 [ 36   0  21 ...   1  80   0]]
[1 1 1 0 1 0 0 1 1 0 1 1 0 1 0 1 1 0 0 1 1 1 1 1 1 0 1 1 1 0 1 0 1 1 0 1 0
 1 1 1 1 0 0

In [5]:
train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.2, random_state = 42)



In [6]:
linear = linear_model.LinearRegression()

linear.fit(train_x, train_y)
acc = linear.score(test_x, test_y)
print(acc)

1.0


In [7]:
print('Coefficient: \n', linear.coef_)
print('Intercept: \n', linear.intercept_)

Coefficient: 
 [ 2.40593635e-17 -1.00660574e-15  4.62408057e-17  1.74857347e-15
 -1.37378332e-15 -1.85036146e-17  2.53747947e-16  4.39865399e-16
 -1.75144552e-17  2.58561741e-17 -1.25431978e-17  1.00000000e+00]
Intercept: 
 4.440892098500626e-16


In [8]:
predictions = linear.predict(test_x)

for x in range(len(predictions)):
    print(predictions[x], test_x[x], test_y[x])

    
#test_y

0.9999999999999999 [51  1 24  1  1 36  0  0 77  0  9  1] 1
0.9999999999999998 [ 46   1  49   1   1  64   0   1  25   0 179   1] 1
0.999999999999998 [ 89   1  37   1   2  64   2   1  95   0 191   1] 1
1.0000000000000016 [26  0 24  1  1  8  0  0  9  1 51  1] 1
1.0000000000000007 [ 42   0  73   0   1  48   0   1  48   0 134   1] 1
-1.9819318832282242e-15 [10  1 16  1  2 20  2  0 27  1 87  0] 0
-1.2165888721739858e-15 [ 7  0 13  0  1 14  0  1 27  1 63  0] 0
1.0000000000000024 [41  0 85  1  1 58  0  0 72  0 76  1] 1
1.0000000000000004 [ 64   1  66   1   1  64   0   1  63   0 165   1] 1
1.000000000000003 [74  0 55  0  1 15  0  1 22  0 16  1] 1
-5.556625364632766e-16 [ 46   1  35   1   2  27   2   0  27   0 100   0] 0
1.0000000000000016 [40  0 69  0  1 64  0  0  3  1 37  1] 1
-9.75501257795906e-16 [ 12   0  37   0   1  20   0   0   9   0 121   0] 0
1.6721880265573507e-15 [25  0 55  0  1 20  0  0  7  0  4  0] 0
1.0000000000000029 [86  1 80  1  1 42  0  0 42  0 92  1] 1
-1.7592855125262216e-15 

In [9]:
#predictions[0:10]

In [10]:
## Mean square error
np.mean((predictions-test_y)**2)

2.7304170004218554e-30